
import { npss_core_api_process_log } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  npss_core_api_process_logEntity implements npss_core_api_process_log{
    @ApiProperty({example:"bigint"})
    npsscapl_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    process_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    processing_system:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    response_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    process_ref_no:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    request_data_json:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    response_data_json:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    currency:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    accountholderbic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    accountnumber:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    datasource:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    senderbic:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    fromdate:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    todate:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    reftype:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ref:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    datetime:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cyclenumber:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    pl_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    fromtime:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    totime:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}
      
export class  npss_core_api_process_log_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    npsscapl_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    process_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    processing_system:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    response_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    process_ref_no:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    request_data_json:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    response_data_json:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    currency:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    accountholderbic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    accountnumber:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    datasource:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    senderbic:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    fromdate:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    todate:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    reftype:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ref:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    datetime:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cyclenumber:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    pl_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    fromtime:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    totime:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}


export { npss_core_api_process_log };