
import { npss_camt_acc_crdr_ntfn } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  npss_camt_acc_crdr_ntfnEntity implements Omit<npss_camt_acc_crdr_ntfn,"limit_amount">{
    @ApiProperty({example:"bigint"})
    ncacn_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    header_msg_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    notification_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ntfn_created_datetime:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    iban:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    currency:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    limit_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cr_dr_indicator:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ntfn_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    booking_datetime:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    end_to_end_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    message_data:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ntfn_account_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    account_type_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_tran_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_domain_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_tran_prop_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    dbtr_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cdtr_acct_id:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}
      
export class  npss_camt_acc_crdr_ntfn_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    ncacn_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    header_msg_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    notification_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ntfn_created_datetime:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    iban:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    currency:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    limit_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cr_dr_indicator:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ntfn_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    booking_datetime:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    end_to_end_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    message_data:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    ntfn_account_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    account_type_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_tran_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_domain_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_tran_prop_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    dbtr_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cdtr_acct_id:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}


export { npss_camt_acc_crdr_ntfn };