
import { npss_merchant_proxy } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  npss_merchant_proxyEntity implements npss_merchant_proxy{
    @ApiProperty({example:"bigint"})
    npssmp_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    product_code:string;
    @ApiProperty({example:"string"})
    bankuserid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    group_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    merchant_tag:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    merchant_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    surname:string;
    @ApiProperty({example:"string"})
    denomination:string;
    @ApiProperty({example:"string"})
    vat_number:string;
    @ApiProperty({example:"string"})
    mcc:string;
    @ApiProperty({example:"string"})
    mobile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    proxy_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    proxy_value:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    document_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    logo:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    exhf_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_refno:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_userid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_product:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_sub_product:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_tran_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    operation_date:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    operation_type:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}
      
export class  npss_merchant_proxy_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    npssmp_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    product_code:string;
    @ApiProperty({example:"string"})
    bankuserid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    group_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    merchant_tag:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    merchant_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    surname:string;
    @ApiProperty({example:"string"})
    denomination:string;
    @ApiProperty({example:"string"})
    vat_number:string;
    @ApiProperty({example:"string"})
    mcc:string;
    @ApiProperty({example:"string"})
    mobile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    proxy_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    proxy_value:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    document_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    logo:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    exhf_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_refno:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_userid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_product:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_sub_product:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    channel_tran_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    operation_date:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    operation_type:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}


export { npss_merchant_proxy };