
import { integration_source } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  integration_sourceEntity implements integration_source{
    @ApiProperty({example:"bigint"})
    integration_source_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    source_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    source_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    source_category_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    connector_type_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    base_url:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    auth_method_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    credential_ref:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    schedule_cron:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    timeout_seconds:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    retry_limit:number;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_enabled:boolean;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    last_run_on:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    last_run_status:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    owner_user_id:bigint;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_active:boolean;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  integration_source_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    integration_source_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    source_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    source_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    source_category_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    connector_type_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    base_url:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    auth_method_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    credential_ref:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    schedule_cron:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    timeout_seconds:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    retry_limit:number;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_enabled:boolean;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    last_run_on:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    last_run_status:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    owner_user_id:bigint;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_active:boolean;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { integration_source };