
import { npss_camt_acc_stmt } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  npss_camt_acc_stmtEntity implements Omit<npss_camt_acc_stmt,"balance_amount"|"balance_amount_1"|"sum_indv_entries"|"sum_net_entries"|"sum_cr_entries"|"sum_db_entries"|"entry_amount"|"orig_amount"|"instd_amount"|"txn_amount"|"batch_tot_amount"|"cash_txn_amount">{
    @ApiProperty({example:"bigint"})
    ncas_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_id:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    hdr_created_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_orgid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_org_bic:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    hdr_msg_pgnb:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_last_pg_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_addtlinf:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    stmt_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    stmt_sequence_number:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_created_date_time:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_from_to_date_time:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_to_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    stmt_copy_dup_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    svcr_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instn_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    parent_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    parent_svcr_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    parent_inst_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type_code_prop:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type_prop:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    balance_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_crdb_ind:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type_prop_1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_cur_1:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    balance_amount_1: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_crdb_ind_1:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date_1:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date_time_1:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    count_indv_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_indv_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    count_net_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_net_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    net_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    tot_cr_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_cr_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    tot_db_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_db_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_ref:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    entry_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_status:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    entry_bk_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    entry_bk_date_time:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    value_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    value_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    acct_serv_ref:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_code_prop:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    orig_amount: number | null;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    instd_amount: number | null;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    txn_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    batch_msg_id:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    batch_txn_count:number;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    batch_tot_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    batch_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    payment_info_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_ref_msgid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_accsvc_ref:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    payment_info_instd_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    payment_info_ete_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    uetr:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mandate_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cheque_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    clr_system_ref:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    cash_txn_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructing_agent_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructing_fin_inst_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructing_fin_inst_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructed_agent_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructed_fin_inst_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructed_fin_inst_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    dbtr_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    dbtr_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cdtr_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cdtr_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    message_data:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_ref_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instd_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    batch_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_dtls_cur:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}
      
export class  npss_camt_acc_stmt_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    ncas_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_id:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    hdr_created_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_orgid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_rcpt_org_bic:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    hdr_msg_pgnb:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_last_pg_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hdr_msg_addtlinf:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    stmt_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    stmt_sequence_number:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_created_date_time:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_from_to_date_time:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_to_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    stmt_copy_dup_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    svcr_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instn_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    parent_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    parent_svcr_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    parent_inst_acct_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type_code_prop:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type_prop:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    balance_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_crdb_ind:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_type_prop_1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_cur_1:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    balance_amount_1: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_crdb_ind_1:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date_1:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    stmt_bal_date_time_1:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    count_indv_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_indv_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    count_net_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_net_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    net_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    tot_cr_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_cr_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    tot_db_entries:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    sum_db_entries: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_ref:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    entry_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_status:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    entry_bk_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    entry_bk_date_time:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    value_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    value_date_time:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    acct_serv_ref:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_code_prop:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    orig_amount: number | null;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    instd_amount: number | null;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    txn_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    batch_msg_id:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    batch_txn_count:number;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    batch_tot_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    batch_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    payment_info_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_ref_msgid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_accsvc_ref:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    payment_info_instd_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    payment_info_ete_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    uetr:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mandate_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cheque_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    clr_system_ref:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    cash_txn_amount: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_crdb_ind:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructing_agent_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructing_fin_inst_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructing_fin_inst_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructed_agent_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructed_fin_inst_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instructed_fin_inst_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    dbtr_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    dbtr_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cdtr_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    cdtr_bic:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    message_data:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    entry_ref_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    instd_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    balance_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    batch_cur:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    txn_dtls_cur:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}


export { npss_camt_acc_stmt };