apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ct006-hrm-uf-generator-httproute
  namespace: ct006-hrm-uf-v1
spec:
  parentRefs:
    - name: tgaprod-gw
      namespace: kgateway-system
      sectionName: https
  hostnames:
    - "tgaprod910.toruslowcode.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ct006/ecp/hrm/v1
      backendRefs:
        - name: ct006-hrm-uf-generator
          port: 443