apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ct001-ta-uf-generator-httproute
  namespace: ct001-ta-uf-v1
spec:
  parentRefs:
    - name: tgatest-gw
      namespace: kgateway-system
      sectionName: https
  hostnames:
    - "tgatest910.toruslowcode.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ct001/tam/ta/v1
      backendRefs:
        - name: ct001-ta-uf-generator
          port: 443