
import { wps_mohre_employee_dtl } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  wps_mohre_employee_dtlEntity implements Omit<wps_mohre_employee_dtl,"total_salary">{
    @ApiProperty({example:"bigint"})
    wpsmed_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    wpsmac_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_mol_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_mol_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_reg_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_eid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mohre_reg_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_card_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_unified_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_eid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_is_active:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_passport_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_name_ar:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    total_salary: number | null;
    @Transform(({ value }) => value?.toISOString().split('T')[0])
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    status_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_iban:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  wps_mohre_employee_dtl_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    wpsmed_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    wpsmac_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_mol_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_mol_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_reg_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_eid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mohre_reg_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_card_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_unified_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_eid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_is_active:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_passport_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_name_ar:string;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    total_salary: number | null;
    @Transform(({ value }) => value?.toISOString().split('T')[0])
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    status_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_iban:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { wps_mohre_employee_dtl };