import React from 'react'
import ContextSelector from './components/ContextSelector'

export const metadata: Metadata = {
  title: 'TestApplication | select-context',
  description: 'Generated by Torus',
};

const page = async() => {
  return (
    <div>
        <ContextSelector />
    </div>
  )
}

export default page
