
import { claims } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  claimsEntity implements claims{
    @ApiProperty({example:"number"})
    claim_id:number;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    employee_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    department_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_grade:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    receipt_image:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    total_amount:number;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    from_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    to_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    claim_category:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    comments:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    expense_date:Date;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_comment_enabled:boolean;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    expense_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    manager_comments:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    expense_description:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    expense_amount:number;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    category_total_amount:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    claim_expense_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    name:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  claims_OnlyParentEntity {
    @ApiProperty({example:"number"})
    claim_id:number;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    employee_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    department_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_grade:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    receipt_image:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    total_amount:number;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    from_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    to_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    claim_category:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    comments:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    expense_date:Date;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_comment_enabled:boolean;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    expense_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    manager_comments:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    expense_description:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    expense_amount:number;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    category_total_amount:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    claim_expense_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    name:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { claims };