
import { wps_mohre_api_calls } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  wps_mohre_api_callsEntity implements wps_mohre_api_calls{
    @ApiProperty({example:"bigint"})
    wpsm_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    process_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    processing_system:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    response_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_mol_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_mol_numberadditional_info:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    additional_info:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_reg_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_eid:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    service_req:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    service_resp:any;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    service_req_encr:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    service_resp_encr:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    client_req:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    client_resp:any;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_unified_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_unified_number:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  wps_mohre_api_calls_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    wpsm_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    process_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    processing_system:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    response_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_mol_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_mol_numberadditional_info:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    additional_info:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_reg_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_eid:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    service_req:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    service_resp:any;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    service_req_encr:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    service_resp_encr:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    client_req:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    client_resp:any;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employer_unified_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    employee_unified_number:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value?.toISOString())
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { wps_mohre_api_calls };