
import { ai_asset } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  ai_assetEntity implements ai_asset{
    @ApiProperty({example:"bigint"})
    ai_asset_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    asset_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    asset_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    asset_type_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    short_description:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    use_case_code:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    business_unit_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    business_owner_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    technical_owner_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vendor_name:string;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_third_party:boolean;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hosting_location:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    risk_tier_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    risk_tier_source:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    criticality_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    lifecycle_status_code:string;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_customer_facing:boolean;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_automated_decision:boolean;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    current_certification_id:bigint;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    cert_expiry_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    discovery_source_code:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    integration_source_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    external_reference:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    first_discovered_on:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    last_seen_on:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    go_live_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    retirement_date:Date;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    current_version_no:number;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_active:boolean;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_unit_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_owner_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_owner_job_title:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    technical_owner_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    technical_owner_job_title:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_purpose:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}
      
export class  ai_asset_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    ai_asset_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    asset_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    asset_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    asset_type_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    short_description:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    use_case_code:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    business_unit_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    business_owner_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    technical_owner_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    vendor_name:string;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_third_party:boolean;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    hosting_location:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    risk_tier_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    risk_tier_source:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    criticality_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    lifecycle_status_code:string;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_customer_facing:boolean;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_automated_decision:boolean;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    current_certification_id:bigint;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    cert_expiry_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    discovery_source_code:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    integration_source_id:bigint;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    external_reference:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    first_discovered_on:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    last_seen_on:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    go_live_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    retirement_date:Date;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    current_version_no:number;
    @ApiPropertyOptional({example:"boolean"})
    @IsOptional()
    is_active:boolean;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_unit_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_owner_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_owner_job_title:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    technical_owner_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    technical_owner_job_title:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    business_purpose:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { ai_asset };