apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ct005-vgph-df-generator-httproute
  namespace: ct005-vgph-df-v1
spec:
  parentRefs:
    - name: tgatest-gw
      namespace: kgateway-system
      sectionName: https  
  hostnames:
    - "tgatest910.toruslowcode.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ct005/gss/vgph/v1/api/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ct005-vgph-df-generator
          port: 443   
    - matches:
        - path:
            type: Exact
            value: /ct005/gss/vgph/v1/api     
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /
      backendRefs:
        - name: ct005-vgph-df-generator
          port: 443