
import { npss_merchant_shops } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  npss_merchant_shopsEntity implements npss_merchant_shops{
    @ApiProperty({example:"bigint"})
    npssms_id:bigint;
    @ApiProperty({example:"number"})
    npssmp_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    product_code:string;
    @ApiProperty({example:"string"})
    bankuserid:string;
    @ApiProperty({example:"string"})
    shop_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_mid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_id:string;
    @ApiProperty({example:"string"})
    shop_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_mcc:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_iban:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    building:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    street:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    postal_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    county:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    exhf_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_account_id:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}
      
export class  npss_merchant_shops_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    npssms_id:bigint;
    @ApiProperty({example:"number"})
    npssmp_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    product_code:string;
    @ApiProperty({example:"string"})
    bankuserid:string;
    @ApiProperty({example:"string"})
    shop_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_mid:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_id:string;
    @ApiProperty({example:"string"})
    shop_type:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_mcc:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_iban:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    building:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    street:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    postal_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    county:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country:string;
    @ApiPropertyOptional({example:"number"})
    @IsOptional()
    exhf_id:number;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    shop_account_id:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_prev_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_next_process_status:string;
}


export { npss_merchant_shops };