
import { hrm_employees } from '@prisma/client';
import { IsEnum,IsOptional } from 'class-validator';
import { ApiProperty,ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';



export class  hrm_employeesEntity implements Omit<hrm_employees,"current_salary"|"annual_ctc">{
    @ApiProperty({example:"bigint"})
    employee_id:bigint;
    @ApiProperty({example:"string"})
    employee_code:string;
    @ApiProperty({example:"string"})
    emp_number:string;
    @ApiProperty({example:"string"})
    first_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    middle_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    last_name:string;
    @ApiProperty({example:"string"})
    full_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    preferred_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    gender:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    date_of_birth:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    marital_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    personal_email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    work_email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mobile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    alternate_mobile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_line1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_line2:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    state:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    postal_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    nationality:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    national_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    passport_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    blood_group:string;
    @ApiProperty({example:"string"})
    employment_type:string;
    @ApiProperty({example:"string"})
    employee_status:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiProperty({example:"date"})
    hire_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    confirmation_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    probation_end:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    resignation_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    termination_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    exit_reason:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    work_mode:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    timezone:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    reporting_manager_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    hr_manager_id:bigint;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    current_salary: number | null;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    annual_ctc: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    salary_currency:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_ifsc:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    emergency_contact_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    emergency_contact_phone:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    emergency_contact_relation:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    biometric_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    profile_photo_url:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    linkedin_profile:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    skills_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    education_history_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    certifications_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    family_details_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    additional_details:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    custom_attributes_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    secure_data:any;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    deleted_at:Date;
    @ApiPropertyOptional({example:"string[]"})
    @IsOptional()
    doc_url:string[];
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
    @ApiProperty({example:"bigint"})
    position_id: bigint;
    @ApiProperty({example:"bigint"})
    grade_id: bigint;
}
      
export class  hrm_employees_OnlyParentEntity {
    @ApiProperty({example:"bigint"})
    employee_id:bigint;
    @ApiProperty({example:"string"})
    employee_code:string;
    @ApiProperty({example:"string"})
    emp_number:string;
    @ApiProperty({example:"string"})
    first_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    middle_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    last_name:string;
    @ApiProperty({example:"string"})
    full_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    preferred_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    gender:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    date_of_birth:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    marital_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    personal_email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    work_email:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    mobile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    alternate_mobile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_line1:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    address_line2:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    city:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    state:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    country:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    postal_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    nationality:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    national_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    passport_number:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    blood_group:string;
    @ApiProperty({example:"string"})
    employment_type:string;
    @ApiProperty({example:"string"})
    employee_status:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiProperty({example:"date"})
    hire_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    confirmation_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    probation_end:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    resignation_date:Date;
    @Transform(({ value }) => value instanceof Date ? value.toISOString().split('T')[0] : value)
    @ApiPropertyOptional({example:"date"})
    @IsOptional()
    termination_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    exit_reason:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    work_mode:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    timezone:string;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    reporting_manager_id:bigint;
    @ApiPropertyOptional({example:"bigint"})
    @IsOptional()
    hr_manager_id:bigint;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    current_salary: number | null;
    @ApiPropertyOptional({example:"decimal"})
    @IsOptional()
    annual_ctc: number | null;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    salary_currency:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_account:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    bank_ifsc:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    emergency_contact_name:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    emergency_contact_phone:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    emergency_contact_relation:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    biometric_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    profile_photo_url:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    linkedin_profile:string;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    skills_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    education_history_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    certifications_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    family_details_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    additional_details:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    custom_attributes_json:any;
    @ApiPropertyOptional({example:"any"})
    @IsOptional()
    secure_data:any;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    deleted_at:Date;
    @ApiPropertyOptional({example:"string[]"})
    @IsOptional()
    doc_url:string[];
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiProperty({example:"datetime"})
    trs_created_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_created_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_modified_date:Date;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_modified_by:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_process_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_access_profile:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_role_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_ps_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_grp_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_sub_org_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_locked_by:string;
    @Transform(({ value }) => value instanceof Date ? value.toISOString() : value)
    @ApiPropertyOptional({example:"datetime"})
    @IsOptional()
    trs_locked_time:Date;
    @ApiProperty({example:"string"})
    trs_tenant_id:string;
    @ApiProperty({example:"string"})
    trs_app_code:string;
    @ApiProperty({example:"string"})
    trs_product_code:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_process_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_event_status:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_token_id:string;
    @ApiPropertyOptional({example:"string"})
    @IsOptional()
    trs_version:string;
}


export { hrm_employees };